// <auto-generated />
using System;
using KadrySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KadrySystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529222042_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KadrySystem.Models.Должность", b =>
                {
                    b.Property<int>("Код_должности")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Код_должности"));

                    b.Property<string>("Квалификационные_требования")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Оклад")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Код_должности");

                    b.ToTable("Должности");
                });

            modelBuilder.Entity("KadrySystem.Models.Подразделение", b =>
                {
                    b.Property<int>("Код_подразделения")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Код_подразделения"));

                    b.Property<string>("Наименование")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Телефон")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Код_подразделения");

                    b.ToTable("Подразделения");
                });

            modelBuilder.Entity("KadrySystem.Models.Приказ", b =>
                {
                    b.Property<int>("Код_приказа")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Код_приказа"));

                    b.Property<DateTime>("Дата_издания")
                        .HasColumnType("datetime2");

                    b.Property<int>("Код_сотрудника")
                        .HasColumnType("int");

                    b.Property<string>("Номер_приказа")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Основание")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Тип_приказа")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Код_приказа");

                    b.HasIndex("Код_сотрудника");

                    b.ToTable("Приказы");
                });

            modelBuilder.Entity("KadrySystem.Models.Сотрудник", b =>
                {
                    b.Property<int>("Код_сотрудника")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Код_сотрудника"));

                    b.Property<string>("Адрес_регистрации")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Дата_приема")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Дата_рождения")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Дата_увольнения")
                        .HasColumnType("datetime2");

                    b.Property<string>("ИНН")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Код_должности")
                        .HasColumnType("int");

                    b.Property<int>("Код_подразделения")
                        .HasColumnType("int");

                    b.Property<string>("Отчество")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Паспортные_данные")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("СНИЛС")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Телефон")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Код_сотрудника");

                    b.HasIndex("Код_должности");

                    b.HasIndex("Код_подразделения");

                    b.ToTable("Сотрудники");
                });

            modelBuilder.Entity("KadrySystem.Models.ШтатноеРасписание", b =>
                {
                    b.Property<int>("Код_позиции")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Код_позиции"));

                    b.Property<int>("Код_должности")
                        .HasColumnType("int");

                    b.Property<int>("Количество_занятых_ставок")
                        .HasColumnType("int");

                    b.Property<int>("Количество_штатных_единиц")
                        .HasColumnType("int");

                    b.HasKey("Код_позиции");

                    b.HasIndex("Код_должности");

                    b.ToTable("ШтатноеРасписание");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KadrySystem.Models.Приказ", b =>
                {
                    b.HasOne("KadrySystem.Models.Сотрудник", "Сотрудник")
                        .WithMany()
                        .HasForeignKey("Код_сотрудника")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Сотрудник");
                });

            modelBuilder.Entity("KadrySystem.Models.Сотрудник", b =>
                {
                    b.HasOne("KadrySystem.Models.Должность", "Должность")
                        .WithMany()
                        .HasForeignKey("Код_должности")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KadrySystem.Models.Подразделение", "Подразделение")
                        .WithMany()
                        .HasForeignKey("Код_подразделения")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Должность");

                    b.Navigation("Подразделение");
                });

            modelBuilder.Entity("KadrySystem.Models.ШтатноеРасписание", b =>
                {
                    b.HasOne("KadrySystem.Models.Должность", "Должность")
                        .WithMany()
                        .HasForeignKey("Код_должности")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Должность");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
